//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.12 at 07:19:15 PM CET 
//


package ch.cmiag.cdws.mitgliedschaften;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Mitgliedschaft complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Mitgliedschaft">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Gremium">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice minOccurs="0">
 *                   &lt;element name="Gremium" type="{http://www.cmiag.ch/cdws/Mitgliedschaften}Gremium"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Dauer" type="{http://www.cmiag.ch/cdws/Mitgliedschaften}DateTimeFieldType"/>
 *         &lt;element name="Person">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice minOccurs="0">
 *                   &lt;element name="Kontakt" type="{http://www.cmiag.ch/cdws/Mitgliedschaften}Person"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Sitz" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="Funktion" type="{http://www.cmiag.ch/cdws/Mitgliedschaften}MultiLangTextFieldType"/>
 *         &lt;element name="FunktionSortKey" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *       &lt;/sequence>
 *       &lt;attribute name="OBJ_GUID" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="SEQ" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="IDX" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Mitgliedschaft", propOrder = {
    "gremium",
    "dauer",
    "person",
    "sitz",
    "funktion",
    "funktionSortKey"
})
public class Mitgliedschaft {

    @XmlElement(name = "Gremium", required = true)
    protected Mitgliedschaft.Gremium gremium;
    @XmlElement(name = "Dauer", required = true)
    protected DateTimeFieldType dauer;
    @XmlElement(name = "Person", required = true)
    protected Mitgliedschaft.Person person;
    @XmlElement(name = "Sitz", required = true, nillable = true)
    protected BigDecimal sitz;
    @XmlElement(name = "Funktion", required = true)
    protected MultiLangTextFieldType funktion;
    @XmlElement(name = "FunktionSortKey", required = true, nillable = true)
    protected BigDecimal funktionSortKey;
    @XmlAttribute(name = "OBJ_GUID", required = true)
    protected String objguid;
    @XmlAttribute(name = "SEQ")
    protected String seq;
    @XmlAttribute(name = "IDX")
    protected String idx;

    /**
     * Gets the value of the gremium property.
     * 
     * @return
     *     possible object is
     *     {@link Mitgliedschaft.Gremium }
     *     
     */
    public Mitgliedschaft.Gremium getGremium() {
        return gremium;
    }

    /**
     * Sets the value of the gremium property.
     * 
     * @param value
     *     allowed object is
     *     {@link Mitgliedschaft.Gremium }
     *     
     */
    public void setGremium(Mitgliedschaft.Gremium value) {
        this.gremium = value;
    }

    /**
     * Gets the value of the dauer property.
     * 
     * @return
     *     possible object is
     *     {@link DateTimeFieldType }
     *     
     */
    public DateTimeFieldType getDauer() {
        return dauer;
    }

    /**
     * Sets the value of the dauer property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTimeFieldType }
     *     
     */
    public void setDauer(DateTimeFieldType value) {
        this.dauer = value;
    }

    /**
     * Gets the value of the person property.
     * 
     * @return
     *     possible object is
     *     {@link Mitgliedschaft.Person }
     *     
     */
    public Mitgliedschaft.Person getPerson() {
        return person;
    }

    /**
     * Sets the value of the person property.
     * 
     * @param value
     *     allowed object is
     *     {@link Mitgliedschaft.Person }
     *     
     */
    public void setPerson(Mitgliedschaft.Person value) {
        this.person = value;
    }

    /**
     * Gets the value of the sitz property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSitz() {
        return sitz;
    }

    /**
     * Sets the value of the sitz property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSitz(BigDecimal value) {
        this.sitz = value;
    }

    /**
     * Gets the value of the funktion property.
     * 
     * @return
     *     possible object is
     *     {@link MultiLangTextFieldType }
     *     
     */
    public MultiLangTextFieldType getFunktion() {
        return funktion;
    }

    /**
     * Sets the value of the funktion property.
     * 
     * @param value
     *     allowed object is
     *     {@link MultiLangTextFieldType }
     *     
     */
    public void setFunktion(MultiLangTextFieldType value) {
        this.funktion = value;
    }

    /**
     * Gets the value of the funktionSortKey property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFunktionSortKey() {
        return funktionSortKey;
    }

    /**
     * Sets the value of the funktionSortKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFunktionSortKey(BigDecimal value) {
        this.funktionSortKey = value;
    }

    /**
     * Gets the value of the objguid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOBJGUID() {
        return objguid;
    }

    /**
     * Sets the value of the objguid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOBJGUID(String value) {
        this.objguid = value;
    }

    /**
     * Gets the value of the seq property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSEQ() {
        return seq;
    }

    /**
     * Sets the value of the seq property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSEQ(String value) {
        this.seq = value;
    }

    /**
     * Gets the value of the idx property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIDX() {
        return idx;
    }

    /**
     * Sets the value of the idx property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIDX(String value) {
        this.idx = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice minOccurs="0">
     *         &lt;element name="Gremium" type="{http://www.cmiag.ch/cdws/Mitgliedschaften}Gremium"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "gremium"
    })
    public static class Gremium {

        @XmlElement(name = "Gremium")
        protected ch.cmiag.cdws.mitgliedschaften.Gremium gremium;

        /**
         * Gets the value of the gremium property.
         * 
         * @return
         *     possible object is
         *     {@link ch.cmiag.cdws.mitgliedschaften.Gremium }
         *     
         */
        public ch.cmiag.cdws.mitgliedschaften.Gremium getGremium() {
            return gremium;
        }

        /**
         * Sets the value of the gremium property.
         * 
         * @param value
         *     allowed object is
         *     {@link ch.cmiag.cdws.mitgliedschaften.Gremium }
         *     
         */
        public void setGremium(ch.cmiag.cdws.mitgliedschaften.Gremium value) {
            this.gremium = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice minOccurs="0">
     *         &lt;element name="Kontakt" type="{http://www.cmiag.ch/cdws/Mitgliedschaften}Person"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "kontakt"
    })
    public static class Person {

        @XmlElement(name = "Kontakt")
        protected ch.cmiag.cdws.mitgliedschaften.Person kontakt;

        /**
         * Gets the value of the kontakt property.
         * 
         * @return
         *     possible object is
         *     {@link ch.cmiag.cdws.mitgliedschaften.Person }
         *     
         */
        public ch.cmiag.cdws.mitgliedschaften.Person getKontakt() {
            return kontakt;
        }

        /**
         * Sets the value of the kontakt property.
         * 
         * @param value
         *     allowed object is
         *     {@link ch.cmiag.cdws.mitgliedschaften.Person }
         *     
         */
        public void setKontakt(ch.cmiag.cdws.mitgliedschaften.Person value) {
            this.kontakt = value;
        }

    }

}
