//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.12 at 07:19:02 PM CET 
//


package ch.cmiag.cdws.mitglieder;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Mitglied complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Mitglied">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Bild" type="{http://www.cmiag.ch/cdws/Mitglieder}DocumentFieldType"/>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Vorname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Firma" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Ort" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Mitgliedschaften">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element name="Behoerdenmandat" type="{http://www.cmiag.ch/cdws/Mitglieder}Mitgliedschaft"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Geschaefte">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element name="Beteiligung" type="{http://www.cmiag.ch/cdws/Mitglieder}Geschaeft"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Intressenbindungen">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element name="Interessenbindung" type="{http://www.cmiag.ch/cdws/Mitglieder}Interessenbindung"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Partei" type="{http://www.cmiag.ch/cdws/Mitglieder}MultiLangTextFieldType"/>
 *         &lt;element name="Wahlkreis" type="{http://www.cmiag.ch/cdws/Mitglieder}MultiLangTextFieldType"/>
 *         &lt;element name="Homepage" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Ledigname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ParteiZusammengesetzt" type="{http://www.cmiag.ch/cdws/Mitglieder}MultiLangTextFieldType"/>
 *         &lt;element name="Beruf" type="{http://www.cmiag.ch/cdws/Mitglieder}MultiLangTextFieldType"/>
 *         &lt;element name="Wohnort" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="BildVerwendung" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="Fraktion" type="{http://www.cmiag.ch/cdws/Mitglieder}MultiLangTextFieldType"/>
 *         &lt;element name="AkademischerTitel" type="{http://www.cmiag.ch/cdws/Mitglieder}MultiLangTextFieldType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="OBJ_GUID" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="SEQ" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="IDX" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Mitglied", propOrder = {
    "bild",
    "name",
    "vorname",
    "firma",
    "ort",
    "mitgliedschaften",
    "geschaefte",
    "intressenbindungen",
    "partei",
    "wahlkreis",
    "homepage",
    "ledigname",
    "parteiZusammengesetzt",
    "beruf",
    "wohnort",
    "bildVerwendung",
    "fraktion",
    "akademischerTitel"
})
public class Mitglied {

    @XmlElement(name = "Bild", required = true)
    protected DocumentFieldType bild;
    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "Vorname", required = true)
    protected String vorname;
    @XmlElement(name = "Firma", required = true)
    protected String firma;
    @XmlElement(name = "Ort", required = true)
    protected String ort;
    @XmlElement(name = "Mitgliedschaften", required = true)
    protected Mitglied.Mitgliedschaften mitgliedschaften;
    @XmlElement(name = "Geschaefte", required = true)
    protected Mitglied.Geschaefte geschaefte;
    @XmlElement(name = "Intressenbindungen", required = true)
    protected Mitglied.Intressenbindungen intressenbindungen;
    @XmlElement(name = "Partei", required = true)
    protected MultiLangTextFieldType partei;
    @XmlElement(name = "Wahlkreis", required = true)
    protected MultiLangTextFieldType wahlkreis;
    @XmlElement(name = "Homepage", required = true)
    protected String homepage;
    @XmlElement(name = "Ledigname", required = true)
    protected String ledigname;
    @XmlElement(name = "ParteiZusammengesetzt", required = true)
    protected MultiLangTextFieldType parteiZusammengesetzt;
    @XmlElement(name = "Beruf", required = true)
    protected MultiLangTextFieldType beruf;
    @XmlElement(name = "Wohnort", required = true)
    protected String wohnort;
    @XmlElement(name = "BildVerwendung", required = true, type = Boolean.class, nillable = true)
    protected Boolean bildVerwendung;
    @XmlElement(name = "Fraktion", required = true)
    protected MultiLangTextFieldType fraktion;
    @XmlElement(name = "AkademischerTitel", required = true)
    protected MultiLangTextFieldType akademischerTitel;
    @XmlAttribute(name = "OBJ_GUID", required = true)
    protected String objguid;
    @XmlAttribute(name = "SEQ")
    protected String seq;
    @XmlAttribute(name = "IDX")
    protected String idx;

    /**
     * Gets the value of the bild property.
     * 
     * @return
     *     possible object is
     *     {@link DocumentFieldType }
     *     
     */
    public DocumentFieldType getBild() {
        return bild;
    }

    /**
     * Sets the value of the bild property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocumentFieldType }
     *     
     */
    public void setBild(DocumentFieldType value) {
        this.bild = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the vorname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVorname() {
        return vorname;
    }

    /**
     * Sets the value of the vorname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVorname(String value) {
        this.vorname = value;
    }

    /**
     * Gets the value of the firma property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirma() {
        return firma;
    }

    /**
     * Sets the value of the firma property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirma(String value) {
        this.firma = value;
    }

    /**
     * Gets the value of the ort property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrt() {
        return ort;
    }

    /**
     * Sets the value of the ort property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrt(String value) {
        this.ort = value;
    }

    /**
     * Gets the value of the mitgliedschaften property.
     * 
     * @return
     *     possible object is
     *     {@link Mitglied.Mitgliedschaften }
     *     
     */
    public Mitglied.Mitgliedschaften getMitgliedschaften() {
        return mitgliedschaften;
    }

    /**
     * Sets the value of the mitgliedschaften property.
     * 
     * @param value
     *     allowed object is
     *     {@link Mitglied.Mitgliedschaften }
     *     
     */
    public void setMitgliedschaften(Mitglied.Mitgliedschaften value) {
        this.mitgliedschaften = value;
    }

    /**
     * Gets the value of the geschaefte property.
     * 
     * @return
     *     possible object is
     *     {@link Mitglied.Geschaefte }
     *     
     */
    public Mitglied.Geschaefte getGeschaefte() {
        return geschaefte;
    }

    /**
     * Sets the value of the geschaefte property.
     * 
     * @param value
     *     allowed object is
     *     {@link Mitglied.Geschaefte }
     *     
     */
    public void setGeschaefte(Mitglied.Geschaefte value) {
        this.geschaefte = value;
    }

    /**
     * Gets the value of the intressenbindungen property.
     * 
     * @return
     *     possible object is
     *     {@link Mitglied.Intressenbindungen }
     *     
     */
    public Mitglied.Intressenbindungen getIntressenbindungen() {
        return intressenbindungen;
    }

    /**
     * Sets the value of the intressenbindungen property.
     * 
     * @param value
     *     allowed object is
     *     {@link Mitglied.Intressenbindungen }
     *     
     */
    public void setIntressenbindungen(Mitglied.Intressenbindungen value) {
        this.intressenbindungen = value;
    }

    /**
     * Gets the value of the partei property.
     * 
     * @return
     *     possible object is
     *     {@link MultiLangTextFieldType }
     *     
     */
    public MultiLangTextFieldType getPartei() {
        return partei;
    }

    /**
     * Sets the value of the partei property.
     * 
     * @param value
     *     allowed object is
     *     {@link MultiLangTextFieldType }
     *     
     */
    public void setPartei(MultiLangTextFieldType value) {
        this.partei = value;
    }

    /**
     * Gets the value of the wahlkreis property.
     * 
     * @return
     *     possible object is
     *     {@link MultiLangTextFieldType }
     *     
     */
    public MultiLangTextFieldType getWahlkreis() {
        return wahlkreis;
    }

    /**
     * Sets the value of the wahlkreis property.
     * 
     * @param value
     *     allowed object is
     *     {@link MultiLangTextFieldType }
     *     
     */
    public void setWahlkreis(MultiLangTextFieldType value) {
        this.wahlkreis = value;
    }

    /**
     * Gets the value of the homepage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHomepage() {
        return homepage;
    }

    /**
     * Sets the value of the homepage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHomepage(String value) {
        this.homepage = value;
    }

    /**
     * Gets the value of the ledigname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLedigname() {
        return ledigname;
    }

    /**
     * Sets the value of the ledigname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLedigname(String value) {
        this.ledigname = value;
    }

    /**
     * Gets the value of the parteiZusammengesetzt property.
     * 
     * @return
     *     possible object is
     *     {@link MultiLangTextFieldType }
     *     
     */
    public MultiLangTextFieldType getParteiZusammengesetzt() {
        return parteiZusammengesetzt;
    }

    /**
     * Sets the value of the parteiZusammengesetzt property.
     * 
     * @param value
     *     allowed object is
     *     {@link MultiLangTextFieldType }
     *     
     */
    public void setParteiZusammengesetzt(MultiLangTextFieldType value) {
        this.parteiZusammengesetzt = value;
    }

    /**
     * Gets the value of the beruf property.
     * 
     * @return
     *     possible object is
     *     {@link MultiLangTextFieldType }
     *     
     */
    public MultiLangTextFieldType getBeruf() {
        return beruf;
    }

    /**
     * Sets the value of the beruf property.
     * 
     * @param value
     *     allowed object is
     *     {@link MultiLangTextFieldType }
     *     
     */
    public void setBeruf(MultiLangTextFieldType value) {
        this.beruf = value;
    }

    /**
     * Gets the value of the wohnort property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWohnort() {
        return wohnort;
    }

    /**
     * Sets the value of the wohnort property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWohnort(String value) {
        this.wohnort = value;
    }

    /**
     * Gets the value of the bildVerwendung property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isBildVerwendung() {
        return bildVerwendung;
    }

    /**
     * Sets the value of the bildVerwendung property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBildVerwendung(Boolean value) {
        this.bildVerwendung = value;
    }

    /**
     * Gets the value of the fraktion property.
     * 
     * @return
     *     possible object is
     *     {@link MultiLangTextFieldType }
     *     
     */
    public MultiLangTextFieldType getFraktion() {
        return fraktion;
    }

    /**
     * Sets the value of the fraktion property.
     * 
     * @param value
     *     allowed object is
     *     {@link MultiLangTextFieldType }
     *     
     */
    public void setFraktion(MultiLangTextFieldType value) {
        this.fraktion = value;
    }

    /**
     * Gets the value of the akademischerTitel property.
     * 
     * @return
     *     possible object is
     *     {@link MultiLangTextFieldType }
     *     
     */
    public MultiLangTextFieldType getAkademischerTitel() {
        return akademischerTitel;
    }

    /**
     * Sets the value of the akademischerTitel property.
     * 
     * @param value
     *     allowed object is
     *     {@link MultiLangTextFieldType }
     *     
     */
    public void setAkademischerTitel(MultiLangTextFieldType value) {
        this.akademischerTitel = value;
    }

    /**
     * Gets the value of the objguid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOBJGUID() {
        return objguid;
    }

    /**
     * Sets the value of the objguid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOBJGUID(String value) {
        this.objguid = value;
    }

    /**
     * Gets the value of the seq property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSEQ() {
        return seq;
    }

    /**
     * Sets the value of the seq property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSEQ(String value) {
        this.seq = value;
    }

    /**
     * Gets the value of the idx property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIDX() {
        return idx;
    }

    /**
     * Sets the value of the idx property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIDX(String value) {
        this.idx = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice maxOccurs="unbounded" minOccurs="0">
     *         &lt;element name="Beteiligung" type="{http://www.cmiag.ch/cdws/Mitglieder}Geschaeft"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "beteiligung"
    })
    public static class Geschaefte {

        @XmlElement(name = "Beteiligung")
        protected List<Geschaeft> beteiligung;

        /**
         * Gets the value of the beteiligung property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the beteiligung property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getBeteiligung().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Geschaeft }
         * 
         * 
         */
        public List<Geschaeft> getBeteiligung() {
            if (beteiligung == null) {
                beteiligung = new ArrayList<Geschaeft>();
            }
            return this.beteiligung;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice maxOccurs="unbounded" minOccurs="0">
     *         &lt;element name="Interessenbindung" type="{http://www.cmiag.ch/cdws/Mitglieder}Interessenbindung"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "interessenbindung"
    })
    public static class Intressenbindungen {

        @XmlElement(name = "Interessenbindung")
        protected List<Interessenbindung> interessenbindung;

        /**
         * Gets the value of the interessenbindung property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the interessenbindung property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getInteressenbindung().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Interessenbindung }
         * 
         * 
         */
        public List<Interessenbindung> getInteressenbindung() {
            if (interessenbindung == null) {
                interessenbindung = new ArrayList<Interessenbindung>();
            }
            return this.interessenbindung;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice maxOccurs="unbounded" minOccurs="0">
     *         &lt;element name="Behoerdenmandat" type="{http://www.cmiag.ch/cdws/Mitglieder}Mitgliedschaft"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "behoerdenmandat"
    })
    public static class Mitgliedschaften {

        @XmlElement(name = "Behoerdenmandat")
        protected List<Mitgliedschaft> behoerdenmandat;

        /**
         * Gets the value of the behoerdenmandat property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the behoerdenmandat property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getBehoerdenmandat().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Mitgliedschaft }
         * 
         * 
         */
        public List<Mitgliedschaft> getBehoerdenmandat() {
            if (behoerdenmandat == null) {
                behoerdenmandat = new ArrayList<Mitgliedschaft>();
            }
            return this.behoerdenmandat;
        }

    }

}
