//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.12 at 07:19:02 PM CET 
//


package ch.cmiag.cdws.mitglieder;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ch.cmiag.cdws.mitglieder package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Kontakt_QNAME = new QName("http://www.cmiag.ch/cdws/Mitglieder", "Kontakt");
    private final static QName _DateTimeFieldTypeStart_QNAME = new QName("http://www.cmiag.ch/cdws/Mitglieder", "Start");
    private final static QName _DateTimeFieldTypeEnd_QNAME = new QName("http://www.cmiag.ch/cdws/Mitglieder", "End");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ch.cmiag.cdws.mitglieder
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Mitglied }
     * 
     */
    public Mitglied createMitglied() {
        return new Mitglied();
    }

    /**
     * Create an instance of {@link MultiLangTextFieldType }
     * 
     */
    public MultiLangTextFieldType createMultiLangTextFieldType() {
        return new MultiLangTextFieldType();
    }

    /**
     * Create an instance of {@link DocumentFieldType }
     * 
     */
    public DocumentFieldType createDocumentFieldType() {
        return new DocumentFieldType();
    }

    /**
     * Create an instance of {@link RenditionType }
     * 
     */
    public RenditionType createRenditionType() {
        return new RenditionType();
    }

    /**
     * Create an instance of {@link DateTimeFieldType }
     * 
     */
    public DateTimeFieldType createDateTimeFieldType() {
        return new DateTimeFieldType();
    }

    /**
     * Create an instance of {@link Mitgliedschaft }
     * 
     */
    public Mitgliedschaft createMitgliedschaft() {
        return new Mitgliedschaft();
    }

    /**
     * Create an instance of {@link Geschaeft }
     * 
     */
    public Geschaeft createGeschaeft() {
        return new Geschaeft();
    }

    /**
     * Create an instance of {@link VersionType }
     * 
     */
    public VersionType createVersionType() {
        return new VersionType();
    }

    /**
     * Create an instance of {@link Interessenbindung }
     * 
     */
    public Interessenbindung createInteressenbindung() {
        return new Interessenbindung();
    }

    /**
     * Create an instance of {@link Mitglied.Mitgliedschaften }
     * 
     */
    public Mitglied.Mitgliedschaften createMitgliedMitgliedschaften() {
        return new Mitglied.Mitgliedschaften();
    }

    /**
     * Create an instance of {@link Mitglied.Geschaefte }
     * 
     */
    public Mitglied.Geschaefte createMitgliedGeschaefte() {
        return new Mitglied.Geschaefte();
    }

    /**
     * Create an instance of {@link Mitglied.Intressenbindungen }
     * 
     */
    public Mitglied.Intressenbindungen createMitgliedIntressenbindungen() {
        return new Mitglied.Intressenbindungen();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Mitglied }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cmiag.ch/cdws/Mitglieder", name = "Kontakt")
    public JAXBElement<Mitglied> createKontakt(Mitglied value) {
        return new JAXBElement<Mitglied>(_Kontakt_QNAME, Mitglied.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cmiag.ch/cdws/Mitglieder", name = "Start", scope = DateTimeFieldType.class)
    public JAXBElement<XMLGregorianCalendar> createDateTimeFieldTypeStart(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_DateTimeFieldTypeStart_QNAME, XMLGregorianCalendar.class, DateTimeFieldType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cmiag.ch/cdws/Mitglieder", name = "End", scope = DateTimeFieldType.class)
    public JAXBElement<XMLGregorianCalendar> createDateTimeFieldTypeEnd(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_DateTimeFieldTypeEnd_QNAME, XMLGregorianCalendar.class, DateTimeFieldType.class, value);
    }

}
