//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.12 at 07:19:30 PM CET 
//


package ch.cmiag.cdws.sitzungen;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MultiLangTextFieldType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MultiLangTextFieldType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="de_CH" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="fr_CH" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MultiLangTextFieldType", propOrder = {
    "deCH",
    "frCH"
})
public class MultiLangTextFieldType {

    @XmlElement(name = "de_CH", required = true)
    protected String deCH;
    @XmlElement(name = "fr_CH", required = true)
    protected String frCH;

    /**
     * Gets the value of the deCH property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeCH() {
        return deCH;
    }

    /**
     * Sets the value of the deCH property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeCH(String value) {
        this.deCH = value;
    }

    /**
     * Gets the value of the frCH property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrCH() {
        return frCH;
    }

    /**
     * Sets the value of the frCH property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrCH(String value) {
        this.frCH = value;
    }

}
