//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.12 at 07:19:30 PM CET 
//


package ch.cmiag.cdws.sitzungen;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Sessionsdatum complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Sessionsdatum">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Datum" type="{http://www.cmiag.ch/cdws/Sitzungen}DateTimeFieldType"/>
 *         &lt;element name="Zeit" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Bezeichnung" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="OBJ_GUID" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Sessionsdatum", propOrder = {
    "datum",
    "zeit",
    "bezeichnung"
})
public class Sessionsdatum {

    @XmlElement(name = "Datum", required = true)
    protected DateTimeFieldType datum;
    @XmlElement(name = "Zeit", required = true)
    protected String zeit;
    @XmlElement(name = "Bezeichnung", required = true)
    protected String bezeichnung;
    @XmlAttribute(name = "OBJ_GUID", required = true)
    protected String objguid;

    /**
     * Gets the value of the datum property.
     * 
     * @return
     *     possible object is
     *     {@link DateTimeFieldType }
     *     
     */
    public DateTimeFieldType getDatum() {
        return datum;
    }

    /**
     * Sets the value of the datum property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTimeFieldType }
     *     
     */
    public void setDatum(DateTimeFieldType value) {
        this.datum = value;
    }

    /**
     * Gets the value of the zeit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZeit() {
        return zeit;
    }

    /**
     * Sets the value of the zeit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZeit(String value) {
        this.zeit = value;
    }

    /**
     * Gets the value of the bezeichnung property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBezeichnung() {
        return bezeichnung;
    }

    /**
     * Sets the value of the bezeichnung property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBezeichnung(String value) {
        this.bezeichnung = value;
    }

    /**
     * Gets the value of the objguid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOBJGUID() {
        return objguid;
    }

    /**
     * Sets the value of the objguid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOBJGUID(String value) {
        this.objguid = value;
    }

}
