//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.12 at 07:19:37 PM CET 
//


package ch.cmiag.cdws.traktanden;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ch.cmiag.cdws.traktanden package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Traktandum_QNAME = new QName("http://www.cmiag.ch/cdws/Traktanden", "Traktandum");
    private final static QName _DateTimeFieldTypeStart_QNAME = new QName("http://www.cmiag.ch/cdws/Traktanden", "Start");
    private final static QName _DateTimeFieldTypeEnd_QNAME = new QName("http://www.cmiag.ch/cdws/Traktanden", "End");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ch.cmiag.cdws.traktanden
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Traktandum }
     * 
     */
    public Traktandum createTraktandum() {
        return new Traktandum();
    }

    /**
     * Create an instance of {@link MultiLangTextFieldType }
     * 
     */
    public MultiLangTextFieldType createMultiLangTextFieldType() {
        return new MultiLangTextFieldType();
    }

    /**
     * Create an instance of {@link Unterlage }
     * 
     */
    public Unterlage createUnterlage() {
        return new Unterlage();
    }

    /**
     * Create an instance of {@link DateTimeFieldType }
     * 
     */
    public DateTimeFieldType createDateTimeFieldType() {
        return new DateTimeFieldType();
    }

    /**
     * Create an instance of {@link ch.cmiag.cdws.traktanden.Geschaeft }
     * 
     */
    public ch.cmiag.cdws.traktanden.Geschaeft createGeschaeft() {
        return new ch.cmiag.cdws.traktanden.Geschaeft();
    }

    /**
     * Create an instance of {@link ch.cmiag.cdws.traktanden.Gremium }
     * 
     */
    public ch.cmiag.cdws.traktanden.Gremium createGremium() {
        return new ch.cmiag.cdws.traktanden.Gremium();
    }

    /**
     * Create an instance of {@link ch.cmiag.cdws.traktanden.Sitzung }
     * 
     */
    public ch.cmiag.cdws.traktanden.Sitzung createSitzung() {
        return new ch.cmiag.cdws.traktanden.Sitzung();
    }

    /**
     * Create an instance of {@link Traktandum.Gremium }
     * 
     */
    public Traktandum.Gremium createTraktandumGremium() {
        return new Traktandum.Gremium();
    }

    /**
     * Create an instance of {@link Traktandum.Sitzung }
     * 
     */
    public Traktandum.Sitzung createTraktandumSitzung() {
        return new Traktandum.Sitzung();
    }

    /**
     * Create an instance of {@link Traktandum.Unterlagen }
     * 
     */
    public Traktandum.Unterlagen createTraktandumUnterlagen() {
        return new Traktandum.Unterlagen();
    }

    /**
     * Create an instance of {@link Traktandum.Geschaeft }
     * 
     */
    public Traktandum.Geschaeft createTraktandumGeschaeft() {
        return new Traktandum.Geschaeft();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Traktandum }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cmiag.ch/cdws/Traktanden", name = "Traktandum")
    public JAXBElement<Traktandum> createTraktandum(Traktandum value) {
        return new JAXBElement<Traktandum>(_Traktandum_QNAME, Traktandum.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cmiag.ch/cdws/Traktanden", name = "Start", scope = DateTimeFieldType.class)
    public JAXBElement<XMLGregorianCalendar> createDateTimeFieldTypeStart(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_DateTimeFieldTypeStart_QNAME, XMLGregorianCalendar.class, DateTimeFieldType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cmiag.ch/cdws/Traktanden", name = "End", scope = DateTimeFieldType.class)
    public JAXBElement<XMLGregorianCalendar> createDateTimeFieldTypeEnd(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_DateTimeFieldTypeEnd_QNAME, XMLGregorianCalendar.class, DateTimeFieldType.class, value);
    }

}
