//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.12 at 07:19:30 PM CET 
//


package ch.cmiag.cdws.sitzungen;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ch.cmiag.cdws.sitzungen package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Sitzung_QNAME = new QName("http://www.cmiag.ch/cdws/Sitzungen", "Sitzung");
    private final static QName _DateTimeFieldTypeStart_QNAME = new QName("http://www.cmiag.ch/cdws/Sitzungen", "Start");
    private final static QName _DateTimeFieldTypeEnd_QNAME = new QName("http://www.cmiag.ch/cdws/Sitzungen", "End");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ch.cmiag.cdws.sitzungen
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Sitzung }
     * 
     */
    public Sitzung createSitzung() {
        return new Sitzung();
    }

    /**
     * Create an instance of {@link MultiLangTextFieldType }
     * 
     */
    public MultiLangTextFieldType createMultiLangTextFieldType() {
        return new MultiLangTextFieldType();
    }

    /**
     * Create an instance of {@link Sessionsunterlage }
     * 
     */
    public Sessionsunterlage createSessionsunterlage() {
        return new Sessionsunterlage();
    }

    /**
     * Create an instance of {@link DateTimeFieldType }
     * 
     */
    public DateTimeFieldType createDateTimeFieldType() {
        return new DateTimeFieldType();
    }

    /**
     * Create an instance of {@link Traktandum }
     * 
     */
    public Traktandum createTraktandum() {
        return new Traktandum();
    }

    /**
     * Create an instance of {@link Sessionsdatum }
     * 
     */
    public Sessionsdatum createSessionsdatum() {
        return new Sessionsdatum();
    }

    /**
     * Create an instance of {@link Sitzung.Sessionsunterlagen }
     * 
     */
    public Sitzung.Sessionsunterlagen createSitzungSessionsunterlagen() {
        return new Sitzung.Sessionsunterlagen();
    }

    /**
     * Create an instance of {@link Sitzung.Sessionsdaten }
     * 
     */
    public Sitzung.Sessionsdaten createSitzungSessionsdaten() {
        return new Sitzung.Sessionsdaten();
    }

    /**
     * Create an instance of {@link Sitzung.Traktanden }
     * 
     */
    public Sitzung.Traktanden createSitzungTraktanden() {
        return new Sitzung.Traktanden();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Sitzung }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cmiag.ch/cdws/Sitzungen", name = "Sitzung")
    public JAXBElement<Sitzung> createSitzung(Sitzung value) {
        return new JAXBElement<Sitzung>(_Sitzung_QNAME, Sitzung.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cmiag.ch/cdws/Sitzungen", name = "Start", scope = DateTimeFieldType.class)
    public JAXBElement<XMLGregorianCalendar> createDateTimeFieldTypeStart(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_DateTimeFieldTypeStart_QNAME, XMLGregorianCalendar.class, DateTimeFieldType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cmiag.ch/cdws/Sitzungen", name = "End", scope = DateTimeFieldType.class)
    public JAXBElement<XMLGregorianCalendar> createDateTimeFieldTypeEnd(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_DateTimeFieldTypeEnd_QNAME, XMLGregorianCalendar.class, DateTimeFieldType.class, value);
    }

}
