//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.12 at 07:20:22 PM CET 
//


package ch.cmiag.cdws.geschaefte;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Geschaeft complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Geschaeft">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Geschaeftsnr" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Geschaeftstyp" type="{http://www.cmiag.ch/cdws/Geschaefte}MultiLangTextFieldType"/>
 *         &lt;element name="Geschaeftstyp_ID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="EingereichtVon">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element name="Beteiligung" type="{http://www.cmiag.ch/cdws/Geschaefte}EingereichtVon"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Mitunterzeichner" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="Federfuehrung" type="{http://www.cmiag.ch/cdws/Geschaefte}MultiLangTextFieldType"/>
 *         &lt;element name="BeratendeKommission" type="{http://www.cmiag.ch/cdws/Geschaefte}MultiLangTextFieldType"/>
 *         &lt;element name="Themen">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element name="CustomStichwort" type="{http://www.cmiag.ch/cdws/Geschaefte}Themen"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="VerwendetGeschaeftAuf">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element name="Geschaeft" type="{http://www.cmiag.ch/cdws/Geschaefte}GeschaeftAuf"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="VerwendetGeschaeftVon">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element name="Geschaeft" type="{http://www.cmiag.ch/cdws/Geschaefte}GeschaeftAuf"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="VorstossEingereichtAm" type="{http://www.cmiag.ch/cdws/Geschaefte}DateTimeFieldType"/>
 *         &lt;element name="ZurueckgezogenAm" type="{http://www.cmiag.ch/cdws/Geschaefte}DateTimeFieldType"/>
 *         &lt;element name="Traktandierungen">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element name="Traktandum" type="{http://www.cmiag.ch/cdws/Geschaefte}Traktandum"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ErgaenzendeDokumente">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element name="Dokument" type="{http://www.cmiag.ch/cdws/Geschaefte}Dokument"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="GeschaeftEroeffnet" type="{http://www.cmiag.ch/cdws/Geschaefte}DateTimeFieldType"/>
 *         &lt;element name="BehandlungImGRAm1Traktandierung" type="{http://www.cmiag.ch/cdws/Geschaefte}DateTimeFieldType"/>
 *         &lt;element name="BehandlungImGRAm" type="{http://www.cmiag.ch/cdws/Geschaefte}DateTimeFieldType"/>
 *         &lt;element name="Geschaeftstitel" type="{http://www.cmiag.ch/cdws/Geschaefte}MultiLangTextFieldType"/>
 *         &lt;element name="LetzteBehandlungImRRRRBNr" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="LetzteBehandlungImRRRRBDatum" type="{http://www.cmiag.ch/cdws/Geschaefte}DateTimeFieldType"/>
 *         &lt;element name="Hauptvorstoesser" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Kommissionsvorstoss" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="VorberatendeKommission" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="FederfuehrungName" type="{http://www.cmiag.ch/cdws/Geschaefte}MultiLangTextFieldType"/>
 *         &lt;element name="FederfuehrungKuerzel" type="{http://www.cmiag.ch/cdws/Geschaefte}MultiLangTextFieldType"/>
 *         &lt;element name="Referendum" type="{http://www.cmiag.ch/cdws/Geschaefte}MultiLangTextFieldType"/>
 *         &lt;element name="Referendumsfrist" type="{http://www.cmiag.ch/cdws/Geschaefte}DateTimeFieldType"/>
 *         &lt;element name="ReferendumsfristAbgabeUnterschriften" type="{http://www.cmiag.ch/cdws/Geschaefte}DateTimeFieldType"/>
 *         &lt;element name="Fraktionsvorstoss" type="{http://www.cmiag.ch/cdws/Geschaefte}MultiLangTextFieldType"/>
 *         &lt;element name="Vorstossnummer" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DringlichkeitBeantrag" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="DringlichkeitGewaehrt" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="gewaehrtAm" type="{http://www.cmiag.ch/cdws/Geschaefte}DateTimeFieldType"/>
 *         &lt;element name="RegistraturplanNummern" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Registraturplan" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ZurueckgewiesenAm" type="{http://www.cmiag.ch/cdws/Geschaefte}DateTimeFieldType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="OBJ_GUID" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="SEQ" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="IDX" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Geschaeft", propOrder = {
    "geschaeftsnr",
    "geschaeftstyp",
    "geschaeftstypID",
    "eingereichtVon",
    "mitunterzeichner",
    "federfuehrung",
    "beratendeKommission",
    "themen",
    "verwendetGeschaeftAuf",
    "verwendetGeschaeftVon",
    "vorstossEingereichtAm",
    "zurueckgezogenAm",
    "traktandierungen",
    "ergaenzendeDokumente",
    "geschaeftEroeffnet",
    "behandlungImGRAm1Traktandierung",
    "behandlungImGRAm",
    "geschaeftstitel",
    "letzteBehandlungImRRRRBNr",
    "letzteBehandlungImRRRRBDatum",
    "hauptvorstoesser",
    "kommissionsvorstoss",
    "vorberatendeKommission",
    "federfuehrungName",
    "federfuehrungKuerzel",
    "referendum",
    "referendumsfrist",
    "referendumsfristAbgabeUnterschriften",
    "fraktionsvorstoss",
    "vorstossnummer",
    "dringlichkeitBeantrag",
    "dringlichkeitGewaehrt",
    "gewaehrtAm",
    "registraturplanNummern",
    "registraturplan",
    "zurueckgewiesenAm"
})
public class Geschaeft {

    @XmlElement(name = "Geschaeftsnr", required = true)
    protected String geschaeftsnr;
    @XmlElement(name = "Geschaeftstyp", required = true)
    protected MultiLangTextFieldType geschaeftstyp;
    @XmlElement(name = "Geschaeftstyp_ID", required = true)
    protected String geschaeftstypID;
    @XmlElement(name = "EingereichtVon", required = true)
    protected Geschaeft.EingereichtVon eingereichtVon;
    @XmlElement(name = "Mitunterzeichner", required = true, nillable = true)
    protected BigDecimal mitunterzeichner;
    @XmlElement(name = "Federfuehrung", required = true)
    protected MultiLangTextFieldType federfuehrung;
    @XmlElement(name = "BeratendeKommission", required = true)
    protected MultiLangTextFieldType beratendeKommission;
    @XmlElement(name = "Themen", required = true)
    protected Geschaeft.Themen themen;
    @XmlElement(name = "VerwendetGeschaeftAuf", required = true)
    protected Geschaeft.VerwendetGeschaeftAuf verwendetGeschaeftAuf;
    @XmlElement(name = "VerwendetGeschaeftVon", required = true)
    protected Geschaeft.VerwendetGeschaeftVon verwendetGeschaeftVon;
    @XmlElement(name = "VorstossEingereichtAm", required = true)
    protected DateTimeFieldType vorstossEingereichtAm;
    @XmlElement(name = "ZurueckgezogenAm", required = true)
    protected DateTimeFieldType zurueckgezogenAm;
    @XmlElement(name = "Traktandierungen", required = true)
    protected Geschaeft.Traktandierungen traktandierungen;
    @XmlElement(name = "ErgaenzendeDokumente", required = true)
    protected Geschaeft.ErgaenzendeDokumente ergaenzendeDokumente;
    @XmlElement(name = "GeschaeftEroeffnet", required = true)
    protected DateTimeFieldType geschaeftEroeffnet;
    @XmlElement(name = "BehandlungImGRAm1Traktandierung", required = true)
    protected DateTimeFieldType behandlungImGRAm1Traktandierung;
    @XmlElement(name = "BehandlungImGRAm", required = true)
    protected DateTimeFieldType behandlungImGRAm;
    @XmlElement(name = "Geschaeftstitel", required = true)
    protected MultiLangTextFieldType geschaeftstitel;
    @XmlElement(name = "LetzteBehandlungImRRRRBNr", required = true)
    protected String letzteBehandlungImRRRRBNr;
    @XmlElement(name = "LetzteBehandlungImRRRRBDatum", required = true)
    protected DateTimeFieldType letzteBehandlungImRRRRBDatum;
    @XmlElement(name = "Hauptvorstoesser", required = true)
    protected String hauptvorstoesser;
    @XmlElement(name = "Kommissionsvorstoss", required = true)
    protected String kommissionsvorstoss;
    @XmlElement(name = "VorberatendeKommission", required = true)
    protected String vorberatendeKommission;
    @XmlElement(name = "FederfuehrungName", required = true)
    protected MultiLangTextFieldType federfuehrungName;
    @XmlElement(name = "FederfuehrungKuerzel", required = true)
    protected MultiLangTextFieldType federfuehrungKuerzel;
    @XmlElement(name = "Referendum", required = true)
    protected MultiLangTextFieldType referendum;
    @XmlElement(name = "Referendumsfrist", required = true)
    protected DateTimeFieldType referendumsfrist;
    @XmlElement(name = "ReferendumsfristAbgabeUnterschriften", required = true)
    protected DateTimeFieldType referendumsfristAbgabeUnterschriften;
    @XmlElement(name = "Fraktionsvorstoss", required = true)
    protected MultiLangTextFieldType fraktionsvorstoss;
    @XmlElement(name = "Vorstossnummer", required = true)
    protected String vorstossnummer;
    @XmlElement(name = "DringlichkeitBeantrag", required = true, type = Boolean.class, nillable = true)
    protected Boolean dringlichkeitBeantrag;
    @XmlElement(name = "DringlichkeitGewaehrt", required = true, type = Boolean.class, nillable = true)
    protected Boolean dringlichkeitGewaehrt;
    @XmlElement(required = true)
    protected DateTimeFieldType gewaehrtAm;
    @XmlElement(name = "RegistraturplanNummern", required = true)
    protected String registraturplanNummern;
    @XmlElement(name = "Registraturplan", required = true)
    protected String registraturplan;
    @XmlElement(name = "ZurueckgewiesenAm", required = true)
    protected DateTimeFieldType zurueckgewiesenAm;
    @XmlAttribute(name = "OBJ_GUID", required = true)
    protected String objguid;
    @XmlAttribute(name = "SEQ")
    protected String seq;
    @XmlAttribute(name = "IDX")
    protected String idx;

    /**
     * Gets the value of the geschaeftsnr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGeschaeftsnr() {
        return geschaeftsnr;
    }

    /**
     * Sets the value of the geschaeftsnr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGeschaeftsnr(String value) {
        this.geschaeftsnr = value;
    }

    /**
     * Gets the value of the geschaeftstyp property.
     * 
     * @return
     *     possible object is
     *     {@link MultiLangTextFieldType }
     *     
     */
    public MultiLangTextFieldType getGeschaeftstyp() {
        return geschaeftstyp;
    }

    /**
     * Sets the value of the geschaeftstyp property.
     * 
     * @param value
     *     allowed object is
     *     {@link MultiLangTextFieldType }
     *     
     */
    public void setGeschaeftstyp(MultiLangTextFieldType value) {
        this.geschaeftstyp = value;
    }

    /**
     * Gets the value of the geschaeftstypID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGeschaeftstypID() {
        return geschaeftstypID;
    }

    /**
     * Sets the value of the geschaeftstypID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGeschaeftstypID(String value) {
        this.geschaeftstypID = value;
    }

    /**
     * Gets the value of the eingereichtVon property.
     * 
     * @return
     *     possible object is
     *     {@link Geschaeft.EingereichtVon }
     *     
     */
    public Geschaeft.EingereichtVon getEingereichtVon() {
        return eingereichtVon;
    }

    /**
     * Sets the value of the eingereichtVon property.
     * 
     * @param value
     *     allowed object is
     *     {@link Geschaeft.EingereichtVon }
     *     
     */
    public void setEingereichtVon(Geschaeft.EingereichtVon value) {
        this.eingereichtVon = value;
    }

    /**
     * Gets the value of the mitunterzeichner property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMitunterzeichner() {
        return mitunterzeichner;
    }

    /**
     * Sets the value of the mitunterzeichner property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMitunterzeichner(BigDecimal value) {
        this.mitunterzeichner = value;
    }

    /**
     * Gets the value of the federfuehrung property.
     * 
     * @return
     *     possible object is
     *     {@link MultiLangTextFieldType }
     *     
     */
    public MultiLangTextFieldType getFederfuehrung() {
        return federfuehrung;
    }

    /**
     * Sets the value of the federfuehrung property.
     * 
     * @param value
     *     allowed object is
     *     {@link MultiLangTextFieldType }
     *     
     */
    public void setFederfuehrung(MultiLangTextFieldType value) {
        this.federfuehrung = value;
    }

    /**
     * Gets the value of the beratendeKommission property.
     * 
     * @return
     *     possible object is
     *     {@link MultiLangTextFieldType }
     *     
     */
    public MultiLangTextFieldType getBeratendeKommission() {
        return beratendeKommission;
    }

    /**
     * Sets the value of the beratendeKommission property.
     * 
     * @param value
     *     allowed object is
     *     {@link MultiLangTextFieldType }
     *     
     */
    public void setBeratendeKommission(MultiLangTextFieldType value) {
        this.beratendeKommission = value;
    }

    /**
     * Gets the value of the themen property.
     * 
     * @return
     *     possible object is
     *     {@link Geschaeft.Themen }
     *     
     */
    public Geschaeft.Themen getThemen() {
        return themen;
    }

    /**
     * Sets the value of the themen property.
     * 
     * @param value
     *     allowed object is
     *     {@link Geschaeft.Themen }
     *     
     */
    public void setThemen(Geschaeft.Themen value) {
        this.themen = value;
    }

    /**
     * Gets the value of the verwendetGeschaeftAuf property.
     * 
     * @return
     *     possible object is
     *     {@link Geschaeft.VerwendetGeschaeftAuf }
     *     
     */
    public Geschaeft.VerwendetGeschaeftAuf getVerwendetGeschaeftAuf() {
        return verwendetGeschaeftAuf;
    }

    /**
     * Sets the value of the verwendetGeschaeftAuf property.
     * 
     * @param value
     *     allowed object is
     *     {@link Geschaeft.VerwendetGeschaeftAuf }
     *     
     */
    public void setVerwendetGeschaeftAuf(Geschaeft.VerwendetGeschaeftAuf value) {
        this.verwendetGeschaeftAuf = value;
    }

    /**
     * Gets the value of the verwendetGeschaeftVon property.
     * 
     * @return
     *     possible object is
     *     {@link Geschaeft.VerwendetGeschaeftVon }
     *     
     */
    public Geschaeft.VerwendetGeschaeftVon getVerwendetGeschaeftVon() {
        return verwendetGeschaeftVon;
    }

    /**
     * Sets the value of the verwendetGeschaeftVon property.
     * 
     * @param value
     *     allowed object is
     *     {@link Geschaeft.VerwendetGeschaeftVon }
     *     
     */
    public void setVerwendetGeschaeftVon(Geschaeft.VerwendetGeschaeftVon value) {
        this.verwendetGeschaeftVon = value;
    }

    /**
     * Gets the value of the vorstossEingereichtAm property.
     * 
     * @return
     *     possible object is
     *     {@link DateTimeFieldType }
     *     
     */
    public DateTimeFieldType getVorstossEingereichtAm() {
        return vorstossEingereichtAm;
    }

    /**
     * Sets the value of the vorstossEingereichtAm property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTimeFieldType }
     *     
     */
    public void setVorstossEingereichtAm(DateTimeFieldType value) {
        this.vorstossEingereichtAm = value;
    }

    /**
     * Gets the value of the zurueckgezogenAm property.
     * 
     * @return
     *     possible object is
     *     {@link DateTimeFieldType }
     *     
     */
    public DateTimeFieldType getZurueckgezogenAm() {
        return zurueckgezogenAm;
    }

    /**
     * Sets the value of the zurueckgezogenAm property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTimeFieldType }
     *     
     */
    public void setZurueckgezogenAm(DateTimeFieldType value) {
        this.zurueckgezogenAm = value;
    }

    /**
     * Gets the value of the traktandierungen property.
     * 
     * @return
     *     possible object is
     *     {@link Geschaeft.Traktandierungen }
     *     
     */
    public Geschaeft.Traktandierungen getTraktandierungen() {
        return traktandierungen;
    }

    /**
     * Sets the value of the traktandierungen property.
     * 
     * @param value
     *     allowed object is
     *     {@link Geschaeft.Traktandierungen }
     *     
     */
    public void setTraktandierungen(Geschaeft.Traktandierungen value) {
        this.traktandierungen = value;
    }

    /**
     * Gets the value of the ergaenzendeDokumente property.
     * 
     * @return
     *     possible object is
     *     {@link Geschaeft.ErgaenzendeDokumente }
     *     
     */
    public Geschaeft.ErgaenzendeDokumente getErgaenzendeDokumente() {
        return ergaenzendeDokumente;
    }

    /**
     * Sets the value of the ergaenzendeDokumente property.
     * 
     * @param value
     *     allowed object is
     *     {@link Geschaeft.ErgaenzendeDokumente }
     *     
     */
    public void setErgaenzendeDokumente(Geschaeft.ErgaenzendeDokumente value) {
        this.ergaenzendeDokumente = value;
    }

    /**
     * Gets the value of the geschaeftEroeffnet property.
     * 
     * @return
     *     possible object is
     *     {@link DateTimeFieldType }
     *     
     */
    public DateTimeFieldType getGeschaeftEroeffnet() {
        return geschaeftEroeffnet;
    }

    /**
     * Sets the value of the geschaeftEroeffnet property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTimeFieldType }
     *     
     */
    public void setGeschaeftEroeffnet(DateTimeFieldType value) {
        this.geschaeftEroeffnet = value;
    }

    /**
     * Gets the value of the behandlungImGRAm1Traktandierung property.
     * 
     * @return
     *     possible object is
     *     {@link DateTimeFieldType }
     *     
     */
    public DateTimeFieldType getBehandlungImGRAm1Traktandierung() {
        return behandlungImGRAm1Traktandierung;
    }

    /**
     * Sets the value of the behandlungImGRAm1Traktandierung property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTimeFieldType }
     *     
     */
    public void setBehandlungImGRAm1Traktandierung(DateTimeFieldType value) {
        this.behandlungImGRAm1Traktandierung = value;
    }

    /**
     * Gets the value of the behandlungImGRAm property.
     * 
     * @return
     *     possible object is
     *     {@link DateTimeFieldType }
     *     
     */
    public DateTimeFieldType getBehandlungImGRAm() {
        return behandlungImGRAm;
    }

    /**
     * Sets the value of the behandlungImGRAm property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTimeFieldType }
     *     
     */
    public void setBehandlungImGRAm(DateTimeFieldType value) {
        this.behandlungImGRAm = value;
    }

    /**
     * Gets the value of the geschaeftstitel property.
     * 
     * @return
     *     possible object is
     *     {@link MultiLangTextFieldType }
     *     
     */
    public MultiLangTextFieldType getGeschaeftstitel() {
        return geschaeftstitel;
    }

    /**
     * Sets the value of the geschaeftstitel property.
     * 
     * @param value
     *     allowed object is
     *     {@link MultiLangTextFieldType }
     *     
     */
    public void setGeschaeftstitel(MultiLangTextFieldType value) {
        this.geschaeftstitel = value;
    }

    /**
     * Gets the value of the letzteBehandlungImRRRRBNr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLetzteBehandlungImRRRRBNr() {
        return letzteBehandlungImRRRRBNr;
    }

    /**
     * Sets the value of the letzteBehandlungImRRRRBNr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLetzteBehandlungImRRRRBNr(String value) {
        this.letzteBehandlungImRRRRBNr = value;
    }

    /**
     * Gets the value of the letzteBehandlungImRRRRBDatum property.
     * 
     * @return
     *     possible object is
     *     {@link DateTimeFieldType }
     *     
     */
    public DateTimeFieldType getLetzteBehandlungImRRRRBDatum() {
        return letzteBehandlungImRRRRBDatum;
    }

    /**
     * Sets the value of the letzteBehandlungImRRRRBDatum property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTimeFieldType }
     *     
     */
    public void setLetzteBehandlungImRRRRBDatum(DateTimeFieldType value) {
        this.letzteBehandlungImRRRRBDatum = value;
    }

    /**
     * Gets the value of the hauptvorstoesser property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHauptvorstoesser() {
        return hauptvorstoesser;
    }

    /**
     * Sets the value of the hauptvorstoesser property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHauptvorstoesser(String value) {
        this.hauptvorstoesser = value;
    }

    /**
     * Gets the value of the kommissionsvorstoss property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKommissionsvorstoss() {
        return kommissionsvorstoss;
    }

    /**
     * Sets the value of the kommissionsvorstoss property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKommissionsvorstoss(String value) {
        this.kommissionsvorstoss = value;
    }

    /**
     * Gets the value of the vorberatendeKommission property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVorberatendeKommission() {
        return vorberatendeKommission;
    }

    /**
     * Sets the value of the vorberatendeKommission property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVorberatendeKommission(String value) {
        this.vorberatendeKommission = value;
    }

    /**
     * Gets the value of the federfuehrungName property.
     * 
     * @return
     *     possible object is
     *     {@link MultiLangTextFieldType }
     *     
     */
    public MultiLangTextFieldType getFederfuehrungName() {
        return federfuehrungName;
    }

    /**
     * Sets the value of the federfuehrungName property.
     * 
     * @param value
     *     allowed object is
     *     {@link MultiLangTextFieldType }
     *     
     */
    public void setFederfuehrungName(MultiLangTextFieldType value) {
        this.federfuehrungName = value;
    }

    /**
     * Gets the value of the federfuehrungKuerzel property.
     * 
     * @return
     *     possible object is
     *     {@link MultiLangTextFieldType }
     *     
     */
    public MultiLangTextFieldType getFederfuehrungKuerzel() {
        return federfuehrungKuerzel;
    }

    /**
     * Sets the value of the federfuehrungKuerzel property.
     * 
     * @param value
     *     allowed object is
     *     {@link MultiLangTextFieldType }
     *     
     */
    public void setFederfuehrungKuerzel(MultiLangTextFieldType value) {
        this.federfuehrungKuerzel = value;
    }

    /**
     * Gets the value of the referendum property.
     * 
     * @return
     *     possible object is
     *     {@link MultiLangTextFieldType }
     *     
     */
    public MultiLangTextFieldType getReferendum() {
        return referendum;
    }

    /**
     * Sets the value of the referendum property.
     * 
     * @param value
     *     allowed object is
     *     {@link MultiLangTextFieldType }
     *     
     */
    public void setReferendum(MultiLangTextFieldType value) {
        this.referendum = value;
    }

    /**
     * Gets the value of the referendumsfrist property.
     * 
     * @return
     *     possible object is
     *     {@link DateTimeFieldType }
     *     
     */
    public DateTimeFieldType getReferendumsfrist() {
        return referendumsfrist;
    }

    /**
     * Sets the value of the referendumsfrist property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTimeFieldType }
     *     
     */
    public void setReferendumsfrist(DateTimeFieldType value) {
        this.referendumsfrist = value;
    }

    /**
     * Gets the value of the referendumsfristAbgabeUnterschriften property.
     * 
     * @return
     *     possible object is
     *     {@link DateTimeFieldType }
     *     
     */
    public DateTimeFieldType getReferendumsfristAbgabeUnterschriften() {
        return referendumsfristAbgabeUnterschriften;
    }

    /**
     * Sets the value of the referendumsfristAbgabeUnterschriften property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTimeFieldType }
     *     
     */
    public void setReferendumsfristAbgabeUnterschriften(DateTimeFieldType value) {
        this.referendumsfristAbgabeUnterschriften = value;
    }

    /**
     * Gets the value of the fraktionsvorstoss property.
     * 
     * @return
     *     possible object is
     *     {@link MultiLangTextFieldType }
     *     
     */
    public MultiLangTextFieldType getFraktionsvorstoss() {
        return fraktionsvorstoss;
    }

    /**
     * Sets the value of the fraktionsvorstoss property.
     * 
     * @param value
     *     allowed object is
     *     {@link MultiLangTextFieldType }
     *     
     */
    public void setFraktionsvorstoss(MultiLangTextFieldType value) {
        this.fraktionsvorstoss = value;
    }

    /**
     * Gets the value of the vorstossnummer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVorstossnummer() {
        return vorstossnummer;
    }

    /**
     * Sets the value of the vorstossnummer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVorstossnummer(String value) {
        this.vorstossnummer = value;
    }

    /**
     * Gets the value of the dringlichkeitBeantrag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDringlichkeitBeantrag() {
        return dringlichkeitBeantrag;
    }

    /**
     * Sets the value of the dringlichkeitBeantrag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDringlichkeitBeantrag(Boolean value) {
        this.dringlichkeitBeantrag = value;
    }

    /**
     * Gets the value of the dringlichkeitGewaehrt property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDringlichkeitGewaehrt() {
        return dringlichkeitGewaehrt;
    }

    /**
     * Sets the value of the dringlichkeitGewaehrt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDringlichkeitGewaehrt(Boolean value) {
        this.dringlichkeitGewaehrt = value;
    }

    /**
     * Gets the value of the gewaehrtAm property.
     * 
     * @return
     *     possible object is
     *     {@link DateTimeFieldType }
     *     
     */
    public DateTimeFieldType getGewaehrtAm() {
        return gewaehrtAm;
    }

    /**
     * Sets the value of the gewaehrtAm property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTimeFieldType }
     *     
     */
    public void setGewaehrtAm(DateTimeFieldType value) {
        this.gewaehrtAm = value;
    }

    /**
     * Gets the value of the registraturplanNummern property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegistraturplanNummern() {
        return registraturplanNummern;
    }

    /**
     * Sets the value of the registraturplanNummern property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegistraturplanNummern(String value) {
        this.registraturplanNummern = value;
    }

    /**
     * Gets the value of the registraturplan property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegistraturplan() {
        return registraturplan;
    }

    /**
     * Sets the value of the registraturplan property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegistraturplan(String value) {
        this.registraturplan = value;
    }

    /**
     * Gets the value of the zurueckgewiesenAm property.
     * 
     * @return
     *     possible object is
     *     {@link DateTimeFieldType }
     *     
     */
    public DateTimeFieldType getZurueckgewiesenAm() {
        return zurueckgewiesenAm;
    }

    /**
     * Sets the value of the zurueckgewiesenAm property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTimeFieldType }
     *     
     */
    public void setZurueckgewiesenAm(DateTimeFieldType value) {
        this.zurueckgewiesenAm = value;
    }

    /**
     * Gets the value of the objguid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOBJGUID() {
        return objguid;
    }

    /**
     * Sets the value of the objguid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOBJGUID(String value) {
        this.objguid = value;
    }

    /**
     * Gets the value of the seq property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSEQ() {
        return seq;
    }

    /**
     * Sets the value of the seq property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSEQ(String value) {
        this.seq = value;
    }

    /**
     * Gets the value of the idx property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIDX() {
        return idx;
    }

    /**
     * Sets the value of the idx property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIDX(String value) {
        this.idx = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice maxOccurs="unbounded" minOccurs="0">
     *         &lt;element name="Beteiligung" type="{http://www.cmiag.ch/cdws/Geschaefte}EingereichtVon"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "beteiligung"
    })
    public static class EingereichtVon {

        @XmlElement(name = "Beteiligung")
        protected List<ch.cmiag.cdws.geschaefte.EingereichtVon> beteiligung;

        /**
         * Gets the value of the beteiligung property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the beteiligung property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getBeteiligung().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ch.cmiag.cdws.geschaefte.EingereichtVon }
         * 
         * 
         */
        public List<ch.cmiag.cdws.geschaefte.EingereichtVon> getBeteiligung() {
            if (beteiligung == null) {
                beteiligung = new ArrayList<ch.cmiag.cdws.geschaefte.EingereichtVon>();
            }
            return this.beteiligung;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice maxOccurs="unbounded" minOccurs="0">
     *         &lt;element name="Dokument" type="{http://www.cmiag.ch/cdws/Geschaefte}Dokument"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "dokument"
    })
    public static class ErgaenzendeDokumente {

        @XmlElement(name = "Dokument")
        protected List<Dokument> dokument;

        /**
         * Gets the value of the dokument property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the dokument property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDokument().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Dokument }
         * 
         * 
         */
        public List<Dokument> getDokument() {
            if (dokument == null) {
                dokument = new ArrayList<Dokument>();
            }
            return this.dokument;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice maxOccurs="unbounded" minOccurs="0">
     *         &lt;element name="CustomStichwort" type="{http://www.cmiag.ch/cdws/Geschaefte}Themen"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "customStichwort"
    })
    public static class Themen {

        @XmlElement(name = "CustomStichwort")
        protected List<ch.cmiag.cdws.geschaefte.Themen> customStichwort;

        /**
         * Gets the value of the customStichwort property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the customStichwort property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCustomStichwort().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ch.cmiag.cdws.geschaefte.Themen }
         * 
         * 
         */
        public List<ch.cmiag.cdws.geschaefte.Themen> getCustomStichwort() {
            if (customStichwort == null) {
                customStichwort = new ArrayList<ch.cmiag.cdws.geschaefte.Themen>();
            }
            return this.customStichwort;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice maxOccurs="unbounded" minOccurs="0">
     *         &lt;element name="Traktandum" type="{http://www.cmiag.ch/cdws/Geschaefte}Traktandum"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "traktandum"
    })
    public static class Traktandierungen {

        @XmlElement(name = "Traktandum")
        protected List<Traktandum> traktandum;

        /**
         * Gets the value of the traktandum property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the traktandum property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTraktandum().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Traktandum }
         * 
         * 
         */
        public List<Traktandum> getTraktandum() {
            if (traktandum == null) {
                traktandum = new ArrayList<Traktandum>();
            }
            return this.traktandum;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice maxOccurs="unbounded" minOccurs="0">
     *         &lt;element name="Geschaeft" type="{http://www.cmiag.ch/cdws/Geschaefte}GeschaeftAuf"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "geschaeft"
    })
    public static class VerwendetGeschaeftAuf {

        @XmlElement(name = "Geschaeft")
        protected List<GeschaeftAuf> geschaeft;

        /**
         * Gets the value of the geschaeft property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the geschaeft property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getGeschaeft().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link GeschaeftAuf }
         * 
         * 
         */
        public List<GeschaeftAuf> getGeschaeft() {
            if (geschaeft == null) {
                geschaeft = new ArrayList<GeschaeftAuf>();
            }
            return this.geschaeft;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice maxOccurs="unbounded" minOccurs="0">
     *         &lt;element name="Geschaeft" type="{http://www.cmiag.ch/cdws/Geschaefte}GeschaeftAuf"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "geschaeft"
    })
    public static class VerwendetGeschaeftVon {

        @XmlElement(name = "Geschaeft")
        protected List<GeschaeftAuf> geschaeft;

        /**
         * Gets the value of the geschaeft property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the geschaeft property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getGeschaeft().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link GeschaeftAuf }
         * 
         * 
         */
        public List<GeschaeftAuf> getGeschaeft() {
            if (geschaeft == null) {
                geschaeft = new ArrayList<GeschaeftAuf>();
            }
            return this.geschaeft;
        }

    }

}
