//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.12 at 07:18:50 PM CET 
//


package ch.cmiag.cdws.gremien;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Gremium complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Gremium">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Name" type="{http://www.cmiag.ch/cdws/Gremien}MultiLangTextFieldType"/>
 *         &lt;element name="Aufgabe" type="{http://www.cmiag.ch/cdws/Gremien}MultiLangTextFieldType"/>
 *         &lt;element name="Kontakt" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Zeitraum" type="{http://www.cmiag.ch/cdws/Gremien}DateTimeFieldType"/>
 *         &lt;element name="Gremiumtyp" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Code" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="Mitglieder">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element name="Behoerdenmandat" type="{http://www.cmiag.ch/cdws/Gremien}Mitglied"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Geschaeftslink" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="Geschaefte">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element name="Geschaeft" type="{http://www.cmiag.ch/cdws/Gremien}Geschaeft"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="GruppenName1" type="{http://www.cmiag.ch/cdws/Gremien}MultiLangTextFieldType"/>
 *         &lt;element name="GruppenName2" type="{http://www.cmiag.ch/cdws/Gremien}MultiLangTextFieldType"/>
 *         &lt;element name="GruppenName3" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Postfach" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Strasse1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Strasse2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PLZ" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Ort" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Tel" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Fax" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Homepage" type="{http://www.cmiag.ch/cdws/Gremien}MultiLangTextFieldType"/>
 *         &lt;element name="EMail" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="OBJ_GUID" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="SEQ" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="IDX" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Gremium", propOrder = {
    "name",
    "aufgabe",
    "kontakt",
    "zeitraum",
    "gremiumtyp",
    "code",
    "mitglieder",
    "geschaeftslink",
    "geschaefte",
    "gruppenName1",
    "gruppenName2",
    "gruppenName3",
    "postfach",
    "strasse1",
    "strasse2",
    "plz",
    "ort",
    "tel",
    "fax",
    "homepage",
    "eMail"
})
public class Gremium {

    @XmlElement(name = "Name", required = true)
    protected MultiLangTextFieldType name;
    @XmlElement(name = "Aufgabe", required = true)
    protected MultiLangTextFieldType aufgabe;
    @XmlElement(name = "Kontakt", required = true)
    protected String kontakt;
    @XmlElement(name = "Zeitraum", required = true)
    protected DateTimeFieldType zeitraum;
    @XmlElement(name = "Gremiumtyp", required = true)
    protected String gremiumtyp;
    @XmlElement(name = "Code", required = true, nillable = true)
    protected BigDecimal code;
    @XmlElement(name = "Mitglieder", required = true)
    protected Gremium.Mitglieder mitglieder;
    @XmlElement(name = "Geschaeftslink", required = true, type = Boolean.class, nillable = true)
    protected Boolean geschaeftslink;
    @XmlElement(name = "Geschaefte", required = true)
    protected Gremium.Geschaefte geschaefte;
    @XmlElement(name = "GruppenName1", required = true)
    protected MultiLangTextFieldType gruppenName1;
    @XmlElement(name = "GruppenName2", required = true)
    protected MultiLangTextFieldType gruppenName2;
    @XmlElement(name = "GruppenName3", required = true)
    protected String gruppenName3;
    @XmlElement(name = "Postfach", required = true)
    protected String postfach;
    @XmlElement(name = "Strasse1", required = true)
    protected String strasse1;
    @XmlElement(name = "Strasse2", required = true)
    protected String strasse2;
    @XmlElement(name = "PLZ", required = true)
    protected String plz;
    @XmlElement(name = "Ort", required = true)
    protected String ort;
    @XmlElement(name = "Tel", required = true)
    protected String tel;
    @XmlElement(name = "Fax", required = true)
    protected String fax;
    @XmlElement(name = "Homepage", required = true)
    protected MultiLangTextFieldType homepage;
    @XmlElement(name = "EMail", required = true)
    protected String eMail;
    @XmlAttribute(name = "OBJ_GUID", required = true)
    protected String objguid;
    @XmlAttribute(name = "SEQ")
    protected String seq;
    @XmlAttribute(name = "IDX")
    protected String idx;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link MultiLangTextFieldType }
     *     
     */
    public MultiLangTextFieldType getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link MultiLangTextFieldType }
     *     
     */
    public void setName(MultiLangTextFieldType value) {
        this.name = value;
    }

    /**
     * Gets the value of the aufgabe property.
     * 
     * @return
     *     possible object is
     *     {@link MultiLangTextFieldType }
     *     
     */
    public MultiLangTextFieldType getAufgabe() {
        return aufgabe;
    }

    /**
     * Sets the value of the aufgabe property.
     * 
     * @param value
     *     allowed object is
     *     {@link MultiLangTextFieldType }
     *     
     */
    public void setAufgabe(MultiLangTextFieldType value) {
        this.aufgabe = value;
    }

    /**
     * Gets the value of the kontakt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKontakt() {
        return kontakt;
    }

    /**
     * Sets the value of the kontakt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKontakt(String value) {
        this.kontakt = value;
    }

    /**
     * Gets the value of the zeitraum property.
     * 
     * @return
     *     possible object is
     *     {@link DateTimeFieldType }
     *     
     */
    public DateTimeFieldType getZeitraum() {
        return zeitraum;
    }

    /**
     * Sets the value of the zeitraum property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTimeFieldType }
     *     
     */
    public void setZeitraum(DateTimeFieldType value) {
        this.zeitraum = value;
    }

    /**
     * Gets the value of the gremiumtyp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGremiumtyp() {
        return gremiumtyp;
    }

    /**
     * Sets the value of the gremiumtyp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGremiumtyp(String value) {
        this.gremiumtyp = value;
    }

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCode(BigDecimal value) {
        this.code = value;
    }

    /**
     * Gets the value of the mitglieder property.
     * 
     * @return
     *     possible object is
     *     {@link Gremium.Mitglieder }
     *     
     */
    public Gremium.Mitglieder getMitglieder() {
        return mitglieder;
    }

    /**
     * Sets the value of the mitglieder property.
     * 
     * @param value
     *     allowed object is
     *     {@link Gremium.Mitglieder }
     *     
     */
    public void setMitglieder(Gremium.Mitglieder value) {
        this.mitglieder = value;
    }

    /**
     * Gets the value of the geschaeftslink property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isGeschaeftslink() {
        return geschaeftslink;
    }

    /**
     * Sets the value of the geschaeftslink property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setGeschaeftslink(Boolean value) {
        this.geschaeftslink = value;
    }

    /**
     * Gets the value of the geschaefte property.
     * 
     * @return
     *     possible object is
     *     {@link Gremium.Geschaefte }
     *     
     */
    public Gremium.Geschaefte getGeschaefte() {
        return geschaefte;
    }

    /**
     * Sets the value of the geschaefte property.
     * 
     * @param value
     *     allowed object is
     *     {@link Gremium.Geschaefte }
     *     
     */
    public void setGeschaefte(Gremium.Geschaefte value) {
        this.geschaefte = value;
    }

    /**
     * Gets the value of the gruppenName1 property.
     * 
     * @return
     *     possible object is
     *     {@link MultiLangTextFieldType }
     *     
     */
    public MultiLangTextFieldType getGruppenName1() {
        return gruppenName1;
    }

    /**
     * Sets the value of the gruppenName1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link MultiLangTextFieldType }
     *     
     */
    public void setGruppenName1(MultiLangTextFieldType value) {
        this.gruppenName1 = value;
    }

    /**
     * Gets the value of the gruppenName2 property.
     * 
     * @return
     *     possible object is
     *     {@link MultiLangTextFieldType }
     *     
     */
    public MultiLangTextFieldType getGruppenName2() {
        return gruppenName2;
    }

    /**
     * Sets the value of the gruppenName2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link MultiLangTextFieldType }
     *     
     */
    public void setGruppenName2(MultiLangTextFieldType value) {
        this.gruppenName2 = value;
    }

    /**
     * Gets the value of the gruppenName3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGruppenName3() {
        return gruppenName3;
    }

    /**
     * Sets the value of the gruppenName3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGruppenName3(String value) {
        this.gruppenName3 = value;
    }

    /**
     * Gets the value of the postfach property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPostfach() {
        return postfach;
    }

    /**
     * Sets the value of the postfach property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPostfach(String value) {
        this.postfach = value;
    }

    /**
     * Gets the value of the strasse1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrasse1() {
        return strasse1;
    }

    /**
     * Sets the value of the strasse1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrasse1(String value) {
        this.strasse1 = value;
    }

    /**
     * Gets the value of the strasse2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrasse2() {
        return strasse2;
    }

    /**
     * Sets the value of the strasse2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrasse2(String value) {
        this.strasse2 = value;
    }

    /**
     * Gets the value of the plz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPLZ() {
        return plz;
    }

    /**
     * Sets the value of the plz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPLZ(String value) {
        this.plz = value;
    }

    /**
     * Gets the value of the ort property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrt() {
        return ort;
    }

    /**
     * Sets the value of the ort property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrt(String value) {
        this.ort = value;
    }

    /**
     * Gets the value of the tel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTel() {
        return tel;
    }

    /**
     * Sets the value of the tel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTel(String value) {
        this.tel = value;
    }

    /**
     * Gets the value of the fax property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFax() {
        return fax;
    }

    /**
     * Sets the value of the fax property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFax(String value) {
        this.fax = value;
    }

    /**
     * Gets the value of the homepage property.
     * 
     * @return
     *     possible object is
     *     {@link MultiLangTextFieldType }
     *     
     */
    public MultiLangTextFieldType getHomepage() {
        return homepage;
    }

    /**
     * Sets the value of the homepage property.
     * 
     * @param value
     *     allowed object is
     *     {@link MultiLangTextFieldType }
     *     
     */
    public void setHomepage(MultiLangTextFieldType value) {
        this.homepage = value;
    }

    /**
     * Gets the value of the eMail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEMail() {
        return eMail;
    }

    /**
     * Sets the value of the eMail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEMail(String value) {
        this.eMail = value;
    }

    /**
     * Gets the value of the objguid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOBJGUID() {
        return objguid;
    }

    /**
     * Sets the value of the objguid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOBJGUID(String value) {
        this.objguid = value;
    }

    /**
     * Gets the value of the seq property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSEQ() {
        return seq;
    }

    /**
     * Sets the value of the seq property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSEQ(String value) {
        this.seq = value;
    }

    /**
     * Gets the value of the idx property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIDX() {
        return idx;
    }

    /**
     * Sets the value of the idx property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIDX(String value) {
        this.idx = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice maxOccurs="unbounded" minOccurs="0">
     *         &lt;element name="Geschaeft" type="{http://www.cmiag.ch/cdws/Gremien}Geschaeft"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "geschaeft"
    })
    public static class Geschaefte {

        @XmlElement(name = "Geschaeft")
        protected List<Geschaeft> geschaeft;

        /**
         * Gets the value of the geschaeft property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the geschaeft property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getGeschaeft().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Geschaeft }
         * 
         * 
         */
        public List<Geschaeft> getGeschaeft() {
            if (geschaeft == null) {
                geschaeft = new ArrayList<Geschaeft>();
            }
            return this.geschaeft;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice maxOccurs="unbounded" minOccurs="0">
     *         &lt;element name="Behoerdenmandat" type="{http://www.cmiag.ch/cdws/Gremien}Mitglied"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "behoerdenmandat"
    })
    public static class Mitglieder {

        @XmlElement(name = "Behoerdenmandat")
        protected List<Mitglied> behoerdenmandat;

        /**
         * Gets the value of the behoerdenmandat property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the behoerdenmandat property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getBehoerdenmandat().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Mitglied }
         * 
         * 
         */
        public List<Mitglied> getBehoerdenmandat() {
            if (behoerdenmandat == null) {
                behoerdenmandat = new ArrayList<Mitglied>();
            }
            return this.behoerdenmandat;
        }

    }

}
