//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.12 at 07:18:50 PM CET 
//


package ch.cmiag.cdws.gremien;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ch.cmiag.cdws.gremien package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Gremium_QNAME = new QName("http://www.cmiag.ch/cdws/Gremien", "Gremium");
    private final static QName _DateTimeFieldTypeEnd_QNAME = new QName("http://www.cmiag.ch/cdws/Gremien", "End");
    private final static QName _DateTimeFieldTypeStart_QNAME = new QName("http://www.cmiag.ch/cdws/Gremien", "Start");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ch.cmiag.cdws.gremien
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Gremium }
     * 
     */
    public Gremium createGremium() {
        return new Gremium();
    }

    /**
     * Create an instance of {@link Mitglied }
     * 
     */
    public Mitglied createMitglied() {
        return new Mitglied();
    }

    /**
     * Create an instance of {@link MultiLangTextFieldType }
     * 
     */
    public MultiLangTextFieldType createMultiLangTextFieldType() {
        return new MultiLangTextFieldType();
    }

    /**
     * Create an instance of {@link DateTimeFieldType }
     * 
     */
    public DateTimeFieldType createDateTimeFieldType() {
        return new DateTimeFieldType();
    }

    /**
     * Create an instance of {@link Geschaeft }
     * 
     */
    public Geschaeft createGeschaeft() {
        return new Geschaeft();
    }

    /**
     * Create an instance of {@link Gremium.Mitglieder }
     * 
     */
    public Gremium.Mitglieder createGremiumMitglieder() {
        return new Gremium.Mitglieder();
    }

    /**
     * Create an instance of {@link Gremium.Geschaefte }
     * 
     */
    public Gremium.Geschaefte createGremiumGeschaefte() {
        return new Gremium.Geschaefte();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Gremium }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cmiag.ch/cdws/Gremien", name = "Gremium")
    public JAXBElement<Gremium> createGremium(Gremium value) {
        return new JAXBElement<Gremium>(_Gremium_QNAME, Gremium.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cmiag.ch/cdws/Gremien", name = "End", scope = DateTimeFieldType.class)
    public JAXBElement<XMLGregorianCalendar> createDateTimeFieldTypeEnd(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_DateTimeFieldTypeEnd_QNAME, XMLGregorianCalendar.class, DateTimeFieldType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cmiag.ch/cdws/Gremien", name = "Start", scope = DateTimeFieldType.class)
    public JAXBElement<XMLGregorianCalendar> createDateTimeFieldTypeStart(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_DateTimeFieldTypeStart_QNAME, XMLGregorianCalendar.class, DateTimeFieldType.class, value);
    }

}
